[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
uuid = "0.8"
serde_json = "1.0"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
sha2 = "0.9"
parquet = "4.2.0"
arrow = "4.2.0"

